(defproject com.github.oliyh/martian-suite "0.1.35-SNAPSHOT"
  :description "Client routing for Swagger APIs"
  :url "https://github.com/oliyh/martian"
  :license {:name "The MIT License"
            :url "http://opensource.org/licenses/MIT"}
  :plugins [[lein-modules "0.3.11"]]
  :profiles {:provided {:dependencies [[org.clojure/clojure]
                                       [org.clojure/clojurescript]]}
             :test {:modules {:subprocess "lein"}}}
  :modules {:subprocess nil}
  :managed-dependencies [[com.github.oliyh/martian "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-httpkit "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-clj-http "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-clj-http-lite "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-hato "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-babashka-http-client "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-cljs-http "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-cljs-http-promise "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-re-frame "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-test "0.1.35-SNAPSHOT"]
                         [com.github.oliyh/martian-vcr "0.1.35-SNAPSHOT"]

                         [org.clojure/clojure "1.12.1"]
                         [org.clojure/clojurescript "1.12.42"]
                         [org.clojure/core.async "1.8.741"]
                         [cheshire "6.0.0"]]
  :aliases {"test" ["modules" "do" "test," "install"]
            "install" ["do" ["modules" "install"]]
            "deploy" ["do" ["modules" "deploy" "clojars"]]}
  :release-tasks [["vcs" "assert-committed"]
                  ["change" "version" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-httpkit" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-clj-http" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-clj-http-lite" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-hato" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-babashka-http-client" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-cljs-http" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-cljs-http-promise" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-re-frame" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-test" "leiningen.release/bump-version" "release"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-vcr" "leiningen.release/bump-version" "release"]
                  ["modules" "change" "version" "leiningen.release/bump-version" "release"]
                  ["vcs" "commit"]
                  ["vcs" "tag" "--no-sign"]
                  ["modules" "deploy" "clojars"]
                  ["change" "version" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-httpkit" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-clj-http" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-clj-http-lite" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-hato" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-babashka-http-client" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-cljs-http" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-cljs-http-promise" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-re-frame" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-test" "leiningen.release/bump-version"]
                  ["change" ":managed-dependencies:com.github.oliyh/martian-vcr" "leiningen.release/bump-version"]
                  ["modules" "change" "version" "leiningen.release/bump-version"]
                  ["vcs" "commit"]
                  ["vcs" "push"]])
