name: Clojure CI
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.693
    
      - name: Build Project
        run: clojure -A:fig/simple

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: DeLaGuardo/clojure-lint-action@master
        continue-on-error: true
        with:
          clj-kondo-args: --lint src
          github_token: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-java@v1
        with:
          java-version: '16'
      - name: Setup Clojure
        uses: DeLaGuardo/setup-clojure@3.4
        with:
          cli: 1.10.1.693
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - name: Build Project
        run: |
          make web
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: resources/public # The folder the action should deploy.